name: Create Release

on: workflow_dispatch

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: android
            target: aarch64-linux-android
          - name: windows
            target: x86_64-pc-windows-msvc

    name: Build (${{ matrix.name }})
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: . -> build
          prefix-key: ${{ matrix.target }}

############### ANDROID ##################

      - name: Setup and Patch Dependencies (Android)
        if: matrix.target == 'aarch64-linux-android'
        run: |
          pushd ..
          git clone --revision 44cdd653e2317d300fb8a6c9c36b03f23991e803 https://github.com/emilk/egui.git
          cd egui
          sed -i 's/ui.set_min_width(ui.available_width());/\/\/ ui.set_min_width(ui.available_width());/' crates/egui/src/containers/combo_box.rs
          popd

          echo -e "\negui = { path = '../egui/crates/egui' }" >> Cargo.toml
          echo "egui_extras = { path = '../egui/crates/egui_extras' }" >> Cargo.toml

      - name: Grant execute permission to build script
        if: matrix.target == 'aarch64-linux-android'
        run: chmod +x tools/android/build.sh

      - name: Build Hachimi for Android
        if: matrix.target == 'aarch64-linux-android'
        run: |
          RELEASE=1 ./tools/android/build.sh
        env:
          HACHIMI_IGNORE_DIRTY: "true"

      - name: Attest Android
        if: matrix.target == 'aarch64-linux-android'
        uses: actions/attest@v4
        with:
          subject-path: |
            build/*.so
            build/sha256.json

############### WINDOWS ##################

      - name: Setup and Patch Dependencies (Windows)
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          pushd ..
          git clone --revision 44cdd653e2317d300fb8a6c9c36b03f23991e803 https://github.com/emilk/egui.git
          cd egui
          sed -i 's/ui.set_min_width(ui.available_width());/\/\/ ui.set_min_width(ui.available_width());/' crates/egui/src/containers/combo_box.rs
          cd ..
          git clone --revision 903043939a076dc81e122a1c8451755bfb3979c8 https://github.com/Nekomaru-PKU/egui-directx11.git
          popd

          cat <<EOF >> Cargo.toml

          egui-directx11 = { path = '../egui-directx11' }
          egui = { path = '../egui/crates/egui' }
          egui_extras = { path = '../egui/crates/egui_extras' }
          EOF

      - name: Setup Windows MSVC Cross-Compile Tools
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          sudo apt install -y llvm lld
          sudo ln -sf /usr/bin/llvm-ar /usr/local/bin/llvm-lib

      - name: Install cargo-xwin
        if: matrix.target == 'x86_64-pc-windows-msvc'
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-xwin@0.23.1

      - name: Cache cargo-xwin MSVC CRT & Windows SDK
        if: matrix.target == 'x86_64-pc-windows-msvc'
        uses: actions/cache@v6
        with:
          path: ~/.cache/cargo-xwin
          key: ${{ runner.os }}-xwin-cache-v1

      - name: Build Hachimi for Windows
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          mkdir -p build
          cargo xwin build --target ${{ matrix.target }} --target-dir build --release
          mv build/${{ matrix.target }}/release/hachimi.dll build/
        env:
          HACHIMI_IGNORE_DIRTY: "true"

      - name: Build Cellar
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          git clone --depth 1 --revision d4c3f79801c8131e26df585766c35e5ce11ec57f https://github.com/Hachimi-Hachimi/Cellar
          cd Cellar
          cargo xwin build --target ${{ matrix.target }} --target-dir build --release
          mv build/${{ matrix.target }}/release/cellar.dll build/
          cd ..

      - name: Check out FunnyHoney
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: git clone --depth 1 --revision 418b5348bd9b7376cc7485c591ca69d49aa4d805 https://gitlab.com/LeadRDRK/FunnyHoney.git

      - name: Build Installer
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          git clone --depth 1 --revision 0387eb987aa9bc446415844e321125dff16e210f https://github.com/teiosteppa/Installer
          cp build/hachimi.dll Installer/
          mv Cellar/build/cellar.dll Installer/
          mv FunnyHoney/FunnyHoney.exe Installer/
          cd Installer
          cargo xwin build --target ${{ matrix.target }} --target-dir build --release --features compress_bin
          cd ..
          mv Installer/build/${{ matrix.target }}/release/hachimi_installer.exe build/

      - name: Get checksums for Windows binaries
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: |
          cargo install b3sum --locked --version 1.8.6
          DLL_HASH=$(b3sum --no-names build/hachimi.dll)
          EXE_HASH=$(b3sum --no-names build/hachimi_installer.exe)
          cat <<EOF > build/blake3.json
          {
            "hachimi.dll": "$DLL_HASH",
            "hachimi_installer.exe": "$EXE_HASH"
          }
          EOF

      - name: Attest Windows
        if: matrix.target == 'x86_64-pc-windows-msvc'
        uses: actions/attest@v4
        with:
          subject-path: |
            build/blake3.json
            build/hachimi.dll
            build/hachimi_installer.exe

############### ARTIFACTS ##################

      - name: Upload Android binaries
        if: matrix.target == 'aarch64-linux-android'
        uses: actions/upload-artifact@v7
        with:
          name: android
          path: |
            build/*.so
            build/sha256.json

      - name: Upload Windows binaries
        if: matrix.target == 'x86_64-pc-windows-msvc'
        uses: actions/upload-artifact@v7
        with:
          name: windows
          path: |
            build/blake3.json
            build/hachimi.dll
            build/hachimi_installer.exe

  create-release:
    needs: build
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Get release version
        id: get_info
        run: |
          VERSION=$(awk '/^\[package\]/{flag=1} flag && /^version/{print $3; exit}' Cargo.toml | tr -d '"')
          echo "RELEASE_VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Download all build artifacts
        uses: actions/download-artifact@v8
        with:
          path: artifacts

      - name: Create release notes
        run: |
          if ! git rev-parse "$LATEST_TAG" >/dev/null 2>&1; then
            git tag $LATEST_TAG
          fi

          PREVIOUS_TAG=$(git describe --tags --abbrev=0 "${LATEST_TAG}^" 2>/dev/null || true)
          if [ -z "$PREVIOUS_TAG" ]; then
            PREVIOUS_TAG=$(git rev-list --max-parents=0 HEAD)
          fi

          echo "## What's Changed" > CHANGELOG.md
          COMMIT_HASHES=$(git rev-list --no-merges ${PREVIOUS_TAG}..${LATEST_TAG})

          IFS=$'\n'

          for hash in $COMMIT_HASHES; do
            subject=$(git show -s --format=%s $hash)
            body=$(git show -s --format=%b $hash)
            author_login=$(gh api "repos/${{ github.repository }}/commits/$hash" --jq '.author.login' 2>/dev/null || echo "")
            if [ -n "$author_login" ]; then
              author="$author_login"
            else
              author=$(git show -s --format=%an $hash)
            fi
            short_hash=$(git show -s --format=%h $hash)

            echo "* **$subject**" >> CHANGELOG.md

            if [ -n "$body" ]; then
              echo "$body" | while read -r line; do
                if [ -z "$line" ]; then continue; fi
                clean_line=$(echo "$line" | sed -E 's/^[ \t]*[-*+][ \t]*//')
                echo "    * $clean_line" >> CHANGELOG.md
              done
            fi
            echo "    (by @$author in $short_hash)" >> CHANGELOG.md
            echo "" >> CHANGELOG.md
          done

          unset IFS
        env:
          GH_TOKEN: ${{ github.token }}
          LATEST_TAG: ${{ env.RELEASE_VERSION }}

      - name: Upload binaries to a release
        uses: softprops/action-gh-release@v3
        with:
          body_path: CHANGELOG.md
          files: |
            artifacts/android/*
            artifacts/windows/*
          tag_name: ${{ env.RELEASE_VERSION }}
